language: csharp
mono: none
dotnet: 2.0.0
node_js:
  - 7.4.0
cache:
  yarn: true
  directories:
    - webapp/node_modules
install:
  - cd webapp
  - yarn install
  - yarn build
  - cd ../server
  - dotnet restore
  - cd ..
script:
  - cd webapp
  - yarn test
  - cd ../server/WebAPI.Xunit
  - dotnet test
